version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    restart: always
    environment:
      - FLASK_CONFIG=dev
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://flask_user:flask_password@db:3306/flask_db
    ## volumes:  
      ## - .:/app 
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: flask_root_password
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: flask_password
      MYSQL_DATABASE: flask_db
    volumes:
      - mysql_data:/var/lib/mysql

  

volumes:
  mysql_data:
